### ISSUE TITLE
D&I Committee Chair/Co-Chair Elections

### ISSUE THREAD

**Issue by amelia-gm** [o3de/community#106]
**D&I Committee Chair / Co-Chair elections for 2022**
For the first year of O3DE, there has been no chair for the Diversity & Inclusion (D&I) Committee. It's time to hold some official elections, following some of the proposed guidance but with our own process due to the holiday season and in order to expedite the elections into next year.

**The Chair / Co-Chair roles**
The chair and co-chair serve equivalent roles in the governance of the Committee and are only differentiated by title in that the highest vote-getter is the chair and the second-highest is the co-chair. The chair and co-chair are expected to govern together in an effective way and split their responsibilities to make sure that the Committee operates smoothly and has the availability of a chairperson at any time.

Unless distinctly required, the term "chairperson" refers to either/both of the chair and co-chair. If a chair or co-chair is required to perform a specific responsibility for the SIG they will always be addressed by their official role title.

In particular, if both chairpersons would be unavailable during a period of time, the chair is considered to be an on-call position during this period. As the higher vote-getter they theoretically represent more of the community and should perform in that capacity under extenuating circumstances. This means that if there is an emergency requiring immediate action from the D&I Committee, the chair will be called to perform a responsibility.

**Responsibilities**
•	Schedule and proctor regular committee meetings on a cadence to be determined by the committee.
•	Serve as a source of authority (and ideally wisdom) with regards to diversity and inclusion in the Open 3D Foundation. Chairpersons are the ultimate arbiters of many diversity & inclusion standards, processes, and practices.
•	Participate in the D&I Committee Discord channel and on the GitHub Discussion forums.
•	Serve as a representative of the broader O3DE community to all SIGs, partners, the governing board, and the Linux Foundation.
•	Represent the Committee to O3DE partners, the governing board, and the Linux Foundation.
•	Coordinate with partners and the Linux Foundation regarding official community events.
•	Represent (or select/elect representatives) to maintain relationships with all SIGs as well as the marketing committee.
•	Serve as an arbiter in D&I-related disputes.
•	Long-term planning and strategy for the course of diversity and inclusion initiatives for O3DE.

This is not a complete list of responsibilities, and will be added to and expanded on as we work to more fully define these positions and the role of the D&I Committee in the Foundation. The new Chair and Co-Chair will help to define these roles. 

**Nomination**
Nomination may either be by a community member or self-nomination. A nominee may withdraw from the election at any time for any reason until the election starts on 12/18/21.

**Nomination requirements**
For this election, the only requirement is that the nominee agrees to be able to perform their required duties and has the availability to do so, taking into account the fact that another chairperson will always be available as a point of contact.
Please note: we will likely add requirements for some Linux Foundation training prior to taking the position of Chair or Co-Chair. 

**How to nominate**
Nominate somebody (including yourself) by responding to this issue with:
•	A statement that the nominee should be nominated for a chair position in the Documentation & Community SIG. Nominees are required to provide a statement that they understand the responsibilities and requirements of the role, and promise to faithfully fulfill them and follow all contributor requirements for O3DE.
•	The name under which the nominee should be addressed. Nominees are allowed to contact the election proctor to have this name changed.
•	The GitHub username of the nominee (self-nominations need not include this; it's on your post.)
•	Nominee's Discord username (you must be an active Discord user if you are a chairperson.)

**Election process**
The election will be conducted between 2021-12-18 12:00PM PT and 2022-01-07 12:00PM PT and held through an online poll. Votes will be anonymous and anyone invested in the direction of O3DE may vote. If you choose to vote, we ask that you be familiar with the nominees.

The current interim chair (Amelia Graham-McCann) will announce the results in the d-i-committee Discord and on the d-i-committee O3DE mailing list no later than 2021-01-12 1:00PM PT. At that time if there is a dispute over the result or concern over vote tampering, voting information will be made public to the extent that it can be exported from the polling system and the Committee will conduct an independent audit under the guidance of a higher governing body in the foundation.

The elected chairpersons will begin serving their term on 2022-01-17 at 12AM PT. The D&I Committee chairs will be elected on a 6-month basis. If you have concerns about wanting to replace chairs earlier, please discuss in the request for feedback on Governance.

**Comment by sptramer** [comment]
I would like to nominate @amelia-gm for a chair position.

**Comment by byrcolin** [comment]
I thought we decided in the meeting that the term was 1 year, not 6 months.

**Comment by SLeibrick** [comment]
I'd like to nominate myself, (Suzanne#7353 on discord). I'd like to be addressed as Suzanne, and I understand the responsibilities and requirements of the role, and will follow them faithfully.

**Comment by aFinchy** [comment]
I'd like to nominate myself, (Finchy#5545 on discord). I'd like to be addressed as Finchy/Finch or Amy, and I understand the responsibilities and requirements of the role, and will follow them faithfully.

**Comment by amelia-gm** [comment]
Election Poll is live. The election will run from today 12/17 until 1/7. Results will be announced on 1/8.

**Comment by lmbr-pip** [comment]
Election has occurred, closing out stale issues.
