### ISSUE TITLE
Proposed SIG-'testing' meeting agenda for 06-28-22

### ISSUE THREAD

**Issue by cgalvan** [o3de/community#137]
### Proposed Topic
I would like to discuss moving the `pyside_utils` module out of the `AutomatedTesting` project. It currently in `editor_python_test_tools`, which is only available in the `AutomatedTesting` project. So would like to discuss some options:
1. Moving `pyside_utils` into the `QtForPython` gem
2. Moving all or parts of `editor_python_test_tools` into `<ENGINE_ROOT>/Tools` under `LyTestTools` and/or its own separate module like `EditorTestTools`
3. Something else?

**Comment by Kadino** [comment]
Apologies for missing this in the lead up to today's meeting! This was discussed, and an RFC should be an appropriate next step.
