### ISSUE TITLE
Proposed RFC Suggestion: Discord Forums

### ISSUE THREAD

**Issue by aFinchy** [o3de/community#157]
### Summary:
Currently in the discord we have major issues with issues members are asking being missed or forgotten and then when they are resolved hard to find. This creates a very bad image as people who may want to find something similar to the issue they had run into, they are unable to find. 

[Discord Forums](https://support.discord.com/hc/en-us/articles/6208479917079-Forum-Channels-FAQ)

### Suggestion design description:
The suggestion is to add discords new thread system into the server in replacement or under the 2 following channels. (#general-support & #newmember-q-and-a). Then this will remove the need of the channel (#frequent-q-and-a). 

![bevy-engine-discord-faq-help](https://user-images.githubusercontent.com/80487462/191604287-7cd1980e-156b-451b-9c58-9c5f1fb5445d.png)

### What are the advantages of the suggestion?
Having this setup will allow members to use certain tags and we could even add the solved tag resulting in easier search of questions that have been solved on the discord. 

![search-tag-filters](https://user-images.githubusercontent.com/80487462/191604581-2c7d45da-de0d-40c8-ad70-0c92f27f7601.png)

### Are there any alternatives to this suggestion?
The only alternatives that have been found to resolve this would be using 3rd party tools on paid servers and paid hosting to run and operate this. This new service will allow us to use a tool that fixes these issues till we look into a dedicated solution.

**Comment by tonybalandiuk** [comment]
What happens to the content currently in #newmember-q-and-as ? Does it get lost? are we ok with that?

**Comment by aFinchy** [comment]
The section would be archived on the server and moved to the rest of the archives

**Comment by aFinchy** [comment]
<img width="185" alt="stuff1" src="https://user-images.githubusercontent.com/80487462/191627144-1c4ba679-9acb-44e3-aecd-f5a011ecc773.PNG">

The above image is the current channels that are in the archived section. That way you have a history of them.

**Comment by tonybalandiuk** [comment]
I support this proposal. Having the 2 channels as discussions seems like a much more intuitive interface for questions and answers.

**Comment by lmbr-pip** [comment]
I support this proposal. The current Discord text channels do not operate well as question/answer spaces.

**Comment by chanmosq** [comment]
I fully support this RFC, with consideration of the above comments and suggestions.

**Comment by willihay** [comment]
I also fully support this RFC. Hope we can get this change in before the next release!

**Comment by ParasiteSt** [comment]
I am with Willihay on trying to get his in before the next release. It was brought up as a suggestion just minutes ago in the suggestion channel on discord.

**Comment by aFinchy** [comment]
We have a Tag Limit of 20. I have added the following 20. Does anyone have any suggestions for changes? 

- Resolved
- Rendering
- Audio
- Assets
- Needs Issue
- Website 
- Networking
- New to O3DE
- UI-UX
- Documentation
- Programming/Scripting
- Simulation/Physics
- Animation
- Platform
- Security
- Installation
- GitHub
- Gems
- Core
- Build

Once we get the Okay on the Tags, I can open the channel up.

**Comment by willihay** [comment]
I'd suggest adding these:

- Editor/Prefab
- Testing

To make room, I'd remove these:

- Needs Issue
- Gems

Once you establish these tags and people start using them, what happens if you want to replace one of them later? (We might want to add one for VR/AR at some point.) Does the replaced tag disappear from older posts? Or is it simply no longer able to be added to new posts?

**Comment by aFinchy** [comment]
So, I just tested on the server and if you remove the tag it removes it from the post. If you rename the tag it renames it on that post. 

If you want to search using the search bar, it currently only shows the title. To search for a key word in the message, you need to use the normal discord search option. I will Include guides in the Forum notes. (Might be fixed/altered in future as this is still a new feature). 

Also working on changing those tags.

**Comment by aFinchy** [comment]
Forums are now Live
https://discord.com/channels/805939474655346758/1024745043162050612/1024745043162050612

**Comment by willihay** [comment]
Cool! Hopefully they'll support adding more tags in the future.

**Comment by chanmosq** [comment]
Yeah I can agree with that - I suppose if the Gems tag were omitted, questions about creating Gems (and components) can also belong to the Programming/Scripting tag, or the Build tag if it's about building them. 

Another one you might be able to remove to make space (if needed) is "New to O3DE". I think a question is a question no matter what their level of experience with O3DE has been.

**Comment by willihay** [comment]
> Another one you might be able to remove to make space (if needed) is "New to O3DE". I think a question is a question no matter what their level of experience with O3DE has been.

+1 agree

**Comment by aFinchy** [comment]
For the tags, I have the following, 

- Resolved
- Platform
- Animation
- Simulation/Physics
- Multiplayer
- Assets
- Audio
- Installation/Build
- Gems
- Entity Component Systems
- Script Canvas/Lua
- World Building
- User Interface
- Rendering
- Projects
- Unresolved
- VR
- AI
   
18 Total

Ones to Consider, 

- Character Controller
- Animation
- AI
- Security
- Needs Issue
- GitHub/Website/Docs
- Tutorials

**Comment by willihay** [comment]
Assume you'll alphabetize those when you go back live. ;-) Although I'd make one exception and keep "Resolved" at the top.

What happened to these topics?

- Editor
- Prefab
- Testing

**Comment by chanmosq** [comment]
What's the acceptance status of this RFC?

**Comment by DarklinuxFr** [comment]
a proper support to USD

**Comment by aFinchy** [comment]
Apologies, The Threads have been added and approved. Closing the issue as its also solved. Feel free to open an new issue for any further changes.
