### ISSUE TITLE
Need comments on community Tenets and values

### ISSUE THREAD

**Issue by OBWANDO** [o3de/community#59]
We wanted to start a discussion around our values / tenets for the community. 
This is a starting point, and it would be helpful for us as a community to discuss, modify, and finalize these before launch.

Please use this issue to discuss and hone our tenets.

They are as follows or can be found here:
https://github.com/o3de/foundation/blob/master/tenets.md

**Comment by lmbr-pip** [comment]
There is now a values document in https://github.com/o3de/community/blob/main/values.md so am closing this out as stale, though we always value contributions or discussions in this space.
