### ISSUE TITLE
Proposed SIG-Core meeting agenda for JUNE-10-2021

### ISSUE THREAD

**Issue by OBWANDO** [o3de/community#63]
## Meeting Details

- **Date/Time:** JUN 10, 2021 @ 8:00 pm UTC / 1:00 pm PDT
- **Location:** https://discord.gg/WtmTC6erDP
- **Moderator:** Pratik Patel
- **Note Taker** TBD

The [SIG Meetings](https://github.com/o3de/foundation/tree/master/sigs) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates

First Meeting, no new updates

## Meeting Agenda

- Introductions - Please keep to under 20 seconds.
- Discuss the scope of the SIG and the frequency with which we should meet.
- Go through the charter: https://github.com/o3de/foundation/blob/master/sigs/sig-core/SIG%20Core%20Charter.md 

## Outcomes from Discussion topics

**Discuss outcomes from agenda**

## Action Items

**Create actionable items from proposed topics**

## Open Discussion Items

List any additional items below!

**Comment by lmbr-pip** [comment]
SIG core moved to own repro, closing out stale issues
