### ISSUE TITLE
contributor-cheatsheet file/link is broken in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jeff-luszcz** [o3de/community#64]
In file https://github.com/o3de/community/blob/main/CONTRIBUTING.md
Expected link to go to contributor-cheatsheet but got Page Not Found error

Link goes to https://github.com/o3de/community/blob/main/github.com/o3de/community/contributors/guide/contributor-cheatsheet

which gives a Page Not Found.
Don't see a contributor-cheatsheet in the codebase otherwise I'd file a PR.

Thanks!

**Comment by jeff-luszcz** [comment]
Also link to O3DE Contributor Guide

**Comment by jeff-luszcz** [comment]
Also Mentoring Initiatives link gives Page Not Found

**Comment by lmbr-pip** [comment]
Update on issue:
1. There is no longer a reference to the cheatsheet in the CONTRIBUTING.md - that link has been removed.
2. The mentoring initiative link should be https://github.com/o3de/community/tree/main/mentoring - will file quick PR for that.
