### ISSUE TITLE
List TSC members

### ISSUE THREAD

**Issue by caniszczyk** [o3de/community#65]

**Comment by lmbr-pip** [comment]
Transferring this to TSC repro as that seems a more appropriate place - https://github.com/o3de/tsc/issues

**Comment by lmbr-pip** [comment]
I don't have the power to transfer this issue, so will create issue in TSC repro for this: https://github.com/o3de/tsc/issues/52

Closing out this one as community could not publish list, TSC owns this task (if they feel it has value).
